name: dart_mqtt_server
description: MQTT Broker server app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
